### ISSUE TITLE
Error while Building cause of Deprecated Gradle features

### ISSUE THREAD

**Issue by omar-ez95** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#1]
I follow your steps but when I run it I get this Error:
If you would update the code it would be so nice of you bro:

`./gradlew run

> Task :compileJava FAILED
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/formfiller/model/ResidenceTitleInfoDTO.java:7: error: class, interface, or enum expected
public record ResidenceTitleInfoDTO(Boolean isResidencePermitPresent,
       ^
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/formfiller/model/FormAllDTO.java:3: error: class, interface, or enum expected
public record FormAllDTO(Section2FormInputs section2FormInputs,
       ^
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/formfiller/model/PersonalInfoDTO.java:3: error: class, interface, or enum expected
public record PersonalInfoDTO(String citizenshipValue,
       ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 653ms
1 actionable task: 1 executed`

**Comment by yilmaznaslan** [comment]
What is the json document that you have pasted into https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/blob/bc517b88c5e81fe3a8af792db77d427ffc239e1b/src/main/resources/residentTitleInfoDTO.json ? I can't recreate the bug from the master branch

**Comment by yilmaznaslan** [comment]
Ahh. Now I see. I used *record* which is only supported by java 14. Can you check the `java --version`, probably you are using an java version older than 14

**Comment by omar-ez95** [comment]
yeah this is the problem.
Is there any work around? I don't program in java tbh. 
`openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)`

**Comment by yilmaznaslan** [comment]
I pushed a fix, can you test again

**Comment by omar-ez95** [comment]
now I have a new error:
`./gradlew run

> Task :compileJava FAILED
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/formfiller/business/TerminFinder.java:117: error: cannot find symbol
        logger.info(String.format("Closing the  window handle: %s", handle.stream().toList().get(0)));
                                                                                   ^
  symbol:   method toList()
  location: interface Stream<String>
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/formfiller/business/TerminFinder.java:118: error: cannot find symbol
        driver.switchTo().window(handle.stream().toList().get(0)).close();
                                                ^
  symbol:   method toList()
  location: interface Stream<String>
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/sessionfinder/business/SessionFinder.java:94: error: cannot find symbol
        String dsrid = Arrays.stream(queryStrings.get(0).split("=")).toList().get(1);
                                                                    ^
  symbol:   method toList()
  location: interface Stream<String>
/home/omar-ez/Documents/sudeep/berlin-auslaenderbehorde-termin-bot/src/main/java/org/example/auslanderbehorde/sessionfinder/business/SessionFinder.java:95: error: cannot find symbol
        String dswid = Arrays.stream(queryStrings.get(1).split("=")).toList().get(1);
                                                                    ^
  symbol:   method toList()
  location: interface Stream<String>
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
`

**Comment by yilmaznaslan** [comment]
Yeah that is also because of the older java version installed in your machine. Then I would suggest to run it via docker. I will add this information to readme. For now you can run the script `cd infra && source init_finder.sh` @omar-ez95

**Comment by yilmaznaslan** [comment]
pushed a fix , `./gradlew run` should also work

**Comment by omar-ez95** [comment]
I am very sorry man but it did not work 
`> Task :run FAILED
2023-02-15 23:17:27 INFO FormManager Verifying form: Section4FormInputs{firstName='firstName', lastName='lastName', emailAddress='yilmazn.aslan@gmail.com', birthdate='12.12.2002', isResidencePermitPresent=Optional.empty, residencePermitId=Optional[D12123123], serviceType=EXTEND_A_RESIDENCE_TITLE}
2023-02-15 23:17:27 INFO DriverManager Connecting to selenium host: null
2023-02-15 23:17:27 INFO DriverManager Initializing driver
Feb 15, 2023 11:17:27 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'omar-ez', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-60-generic', java.version: '11.0.17'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-proxy-server, --no-sandbox, --enable-automation, --enableVNC, --disable-dev-shm-usage, --disable-browser-side-navi..., --ignore-certificate-errors], extensions: []}, pageLoadStrategy: none}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-proxy-server, --no-sandbox, --enable-automation, --enableVNC, --disable-dev-shm-usage, --disable-browser-side-navi..., --ignore-certificate-errors], extensions: []}, pageLoadStrategy: none}}]
Capabilities {}
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
        at org.example.auslanderbehorde.formfiller.business.DriverManager.initDriverHeadless(DriverManager.java:35)
        at org.example.auslanderbehorde.formfiller.business.FormManager.startForm(FormManager.java:78)
        at org.example.Main.main(Main.java:18)
Caused by: java.io.UncheckedIOException: java.net.UnknownHostException: null: Temporary failure in name resolution
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:120)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
        ... 6 more
Caused by: java.net.UnknownHostException: null: Temporary failure in name resolution
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:169)
        at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:166)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:166)
        at io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:50)
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)
        at org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:50)
        at org.asynchttpclient.netty.request.NettyRequestSender.resolveAddresses(NettyRequestSender.java:364)
        at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:307)
        at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:143)
        at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:114)
        at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
        at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:228)
        at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:249)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:55)
        ... 19 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date`

**Comment by yilmaznaslan** [comment]
Looks like you didn't add this `export SELENIUM_GRID_HOST='localhost'` into you bash profile or run it in the terminal. Also make sure that you have run the selenium server `source infra/init_seleniumgrid.sh`

**Comment by omar-ez95** [comment]
I have done both 
![sel](https://user-images.githubusercontent.com/83030027/219202926-6bab38da-cc4e-419c-9489-497c5785e376.png)
![error](https://user-images.githubusercontent.com/83030027/219202996-307a79e5-10f7-4f8d-87ac-002812ea17f7.png)

**Comment by yilmaznaslan** [comment]
Try either `export SELENIUM_GRID_HOST="localhost"` or `export SELENIUM_GRID_HOST=localhost`. For some reason creation of env variable SELENIUM_GRID_HOST doesn't work. When you type `printenv` in terminal you should she the SELENIUM_GRID_HOST

**Comment by omar-ez95** [comment]
![env](https://user-images.githubusercontent.com/83030027/219207276-a7aaec60-ef47-48e9-b8b1-ad512603eb62.png)
I have it correct in the env I already checked but some how it is not working

**Comment by omar-ez95** [comment]
Actully removing 'sudo' solved the issue
![env](https://user-images.githubusercontent.com/83030027/219207573-9e95f0a0-52eb-4b39-a1b5-b4fa500a8221.png)
I think it is working right now

**Comment by omar-ez95** [comment]
thank you sooo much man

**Comment by yilmaznaslan** [comment]
You are welcome. But please note it still doesn't cover all the visa types. And ausländerbehörde doesn't release free slot very often. If you email them you could also get help faster
