### ISSUE TITLE
2023-04-21 19:47:31 ERROR TerminFinder Exception occurred during the process, quitting.

### ISSUE THREAD

**Issue by RikotheBest** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#31]
Hi! First of all, thank you for your work! 
I got this error 2 times today when i left my laptop with the bot for a couple of hours. First time it stayed like this till i came home. Then i restarted it and second time it happened it fixed itself like below:

2023-04-21 19:47:31 ERROR TerminFinder Exception occurred during the process, quitting.
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.example.formhandlers.Section2ServiceSelectionHandler$$Lambda$475/0x00000008013c1b38@89a50e0 (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.3.1', java.version: '20.0.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.lTOj8m}, goog:chromeOptions: {debuggerAddress: localhost:36425}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 111.0.5563.146, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2c6252a51ac816e57e69f18ef5f4e078
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87) ~[selenium-support-4.8.1.jar:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231) ~[selenium-support-4.8.1.jar:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.clickVisaPurpose(Section2ServiceSelectionHandler.java:186) ~[main/:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.fillAndSendForm(Section2ServiceSelectionHandler.java:66) ~[main/:?]
        at org.example.TerminFinder.fillAndSendFormWithExceptionHandling(TerminFinder.java:115) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:85) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
2023-04-21 19:47:31 INFO IoUtils File name :exception_2023-04-21_19:47:31_exception.html, exception_2023-04-21_19:47:31_exception.png
2023-04-21 19:47:31 INFO IoUtils Getting the page content
2023-04-21 19:47:31 INFO IoUtils Saving source code to file
2023-04-21 19:47:31 INFO IoUtils Saving screenshot
2023-04-21 19:47:32 INFO IoUtils S3 is not  enabled
2023-04-21 19:47:32 INFO TerminFinder page is saved
2023-04-21 19:47:32 INFO DriverUtils Starting to resetDriverGracefully
2023-04-21 19:47:32 INFO DriverUtils Successfully reset the driver
2023-04-21 19:47:32 INFO DriverUtils Initializing the driver. Host: localhost, try: 0
2023-04-21 19:47:33 INFO DriverUtils Driver is initialized.
2023-04-21 19:47:43 INFO TerminFinder Starting to getHomePage

What could be the reason?

**Comment by yilmaznaslan** [comment]
Hi, 

- the logs you posted are fine. Sometimes page doesn't load in time due to network issues. So in such cases the requests fail and print the exception. As you see at 19:47:43 new iteration starts successfully.
- I am more interested how it got stuck as you. mentioned.  If it stays again and if it can not recover, can you post logs before trying to restart manually

**Comment by RikotheBest** [comment]
sure, here they are. It always happens when my laptop's screen turns off (but it doesn't go to sleep mode)

2023-04-22 13:53:05 ERROR TerminFinder Exception occurred during the process, quitting.
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.example.formhandlers.Section2ServiceSelectionHandler$$Lambda$477/0x00000008013bc7e8@6352f634 (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.3.1', java.version: '20.0.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.xdrmNW}, goog:chromeOptions: {debuggerAddress: localhost:35045}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 111.0.5563.146, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 20e5e319892efdbbb87e96ac6e24ac67
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87) ~[selenium-support-4.8.1.jar:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231) ~[selenium-support-4.8.1.jar:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.clickToVisa(Section2ServiceSelectionHandler.java:204) ~[main/:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.fillAndSendForm(Section2ServiceSelectionHandler.java:68) ~[main/:?]
        at org.example.TerminFinder.fillAndSendFormWithExceptionHandling(TerminFinder.java:115) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:85) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
2023-04-22 13:53:05 INFO IoUtils File name :exception_2023-04-22_13:53:05_exception.html, exception_2023-04-22_13:53:05_exception.png
2023-04-22 13:53:05 INFO IoUtils Getting the page content
2023-04-22 13:53:05 ERROR IoUtils Error occurred during getting the page source. Reason: 
org.openqa.selenium.NoSuchSessionException: Unable to execute request for an existing session: Unable to find session with ID: 20e5e319892efdbbb87e96ac6e24ac67
Build info: version: '4.8.3', revision: 'b19b418e60'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '11.0.18'
Driver info: driver.version: unknown
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.3.1', java.version: '20.0.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [20e5e319892efdbbb87e96ac6e24ac67, getPageSource {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.xdrmNW}, goog:chromeOptions: {debuggerAddress: localhost:35045}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 111.0.5563.146, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 20e5e319892efdbbb87e96ac6e24ac67
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:396) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.example.utils.IoUtils.savePage(IoUtils.java:64) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:96) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
2023-04-22 13:53:05 INFO TerminFinder page is saved
2023-04-22 13:53:05 INFO DriverUtils Starting to resetDriverGracefully
2023-04-22 13:53:05 ERROR DriverUtils Failed to reset the driver. Reason: 
org.openqa.selenium.NoSuchSessionException: Unable to execute request for an existing session: Unable to find session with ID: 20e5e319892efdbbb87e96ac6e24ac67
Build info: version: '4.8.3', revision: 'b19b418e60'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '11.0.18'
Driver info: driver.version: unknown
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.3.1', java.version: '20.0.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [20e5e319892efdbbb87e96ac6e24ac67, close {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.xdrmNW}, goog:chromeOptions: {debuggerAddress: localhost:35045}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 111.0.5563.146, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 20e5e319892efdbbb87e96ac6e24ac67
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:419) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.example.utils.DriverUtils.lambda$resetDriverGracefully$1(DriverUtils.java:60) ~[main/:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208) ~[selenium-support-4.8.1.jar:?]
        at org.example.utils.DriverUtils.resetDriverGracefully(DriverUtils.java:58) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:99) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
2023-04-22 13:53:06 ERROR DriverUtils Failed to reset the driver. Reason: 
org.openqa.selenium.NoSuchSessionException: Unable to execute request for an existing session: Unable to find session with ID: 20e5e319892efdbbb87e96ac6e24ac67

**Comment by RikotheBest** [comment]
and after that like this: 
2023-04-22 19:25:34 INFO DriverUtils Initializing the driver. Host: localhost, try: 10
2023-04-22 19:28:34 ERROR DriverUtils Failed to initialize the driver. Reason: 
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

**Comment by yilmaznaslan** [comment]
:) You need to make sure that your computer and docker keeps running when your screen goes off.


Like in Mac:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/58464107/233827325-00bbee10-4ccd-4cc3-bd9d-fee48e47344b.png">


Closing the issue since it is not related to code
