### ISSUE TITLE
Getting error during image build

### ISSUE THREAD

**Issue by sinankuzu** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#45]
I took a screenshor of the error. What i am doing wrong?
![docker error](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/100736384/f108c671-96a0-45e7-b751-3be4f2bce0bd)

**Comment by yilmaznaslan** [comment]
You dont need to build the docker image. Simply run  `./gradlew run`

**Comment by sinankuzu** [comment]
I am not familiar with the concept so i might trying to silly things :)

**Comment by sinankuzu** [comment]
My java version was 20 so i downgraded to 17. It did work but still i get an error 

2023-05-09 22:18:55 INFO DriverUtils Initializing the driver. Host: localhost, try: 22
2023-05-09 22:18:55 ERROR DriverUtils Failed to initialize the driver. Reason:
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-I89533R', ip: '192.168.178.122'
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-dev-shm-usage, --remote-allow-origins=*, --disable-blink-features=Au..., --disable-infobars, --start-maximized, --disable-extensions, user-agent=Mozilla/5.0 (Win...], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-dev-shm-usage, --remote-allow-origins=*, --disable-blink-features=Au..., --disable-infobars, --start-maximized, --disable-extensions, user-agent=Mozilla/5.0 (Win...], extensions: []}}}]
Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-dev-shm-usage, --remote-allow-origins=*, --disable-blink-features=Au..., --disable-infobars, --start-maximized, --disable-extensions, user-agent=Mozilla/5.0 (Win...], extensions: []}}
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.example.utils.DriverUtils.initDriver(DriverUtils.java:35) [main/:?]
        at org.example.TerminFinder.startScanning(TerminFinder.java:65) [main/:?]
        at org.example.Main.main(Main.java:20) [main/:?]
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:4444
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) ~[selenium-http-4.8.1.jar:?]
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.8.1.jar:?]
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) ~[selenium-http-4.8.1.jar:?]
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.8.1.jar:?]
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51) ~[selenium-remote-driver-4.8.1.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) ~[selenium-remote-driver-4.8.1.jar:?]
        ... 6 more
Caused by: java.net.ConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:4444
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20) ~[async-http-client-2.12.3.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:4444
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
<=========----> 75% EXECUTING [27s]

**Comment by sinankuzu** [comment]
i believe it's working now. I wanted to check http://localhost:7900/?autoconnect=1&resize=scale&password=secret. but it says password check failed.

also can you confirm that it's working that's the latest feedback from terminal and it's still working. 

2023-05-09 22:37:36 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 22:37:37 INFO Section2ServiceSelectionHandler Successfully send form  count is:22
2023-05-09 22:37:37 INFO Section2ServiceSelectionHandler Value of the active step is: 2     
Service selection
2023-05-09 22:37:37 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 22
2023-05-09 22:37:47 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 22:37:47 INFO Section2ServiceSelectionHandler Successfully send form  count is:23
2023-05-09 22:37:47 INFO Section2ServiceSelectionHandler Value of the active step is: 2     
Service selection
2023-05-09 22:37:47 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 23
2023-05-09 22:37:57 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 22:37:57 INFO Section2ServiceSelectionHandler Successfully send form  count is:24
2023-05-09 22:37:57 INFO Section2ServiceSelectionHandler Value of the active step is: 2
Service selection
2023-05-09 22:37:57 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 24
2023-05-09 22:38:07 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 22:38:07 INFO Section2ServiceSelectionHandler Successfully send form  count is:25
2023-05-09 22:38:07 INFO Section2ServiceSelectionHandler Value of the active step is: 2     
Service selection
2023-05-09 22:38:07 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 25
2023-05-09 22:38:17 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 22:38:18 INFO Section2ServiceSelectionHandler Successfully send form  count is:26
2023-05-09 22:38:18 INFO Section2ServiceSelectionHandler Value of the active step is: 2     
Service selection
2023-05-09 22:38:18 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 26
<=========----> 75% EXECUTING [4m 48s]
> :run

**Comment by yilmaznaslan** [comment]
Please pull from master the latest state and rerun ./gradlew run. It looks good but a I pushed a fix a couple of hours ago  for an issue. Your version is old

**Comment by sinankuzu** [comment]
yes thanks! it's working without problem now. I also have the visual from localhost. Thanks again. 

2023-05-09 23:03:39 INFO Section2ServiceSelectionHandler Successfully send form  count is:2
2023-05-09 23:03:39 INFO Section2ServiceSelectionHandler Value of the active step is: 2    
Service selection
2023-05-09 23:03:39 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 2
2023-05-09 23:03:49 INFO Section2ServiceSelectionHandler Starting to fill the form in section 2
2023-05-09 23:03:49 INFO Section2ServiceSelectionHandler Starting to selectCitizenshipValue
2023-05-09 23:03:51 INFO Section2ServiceSelectionHandler Successfully selected the citizenship value
2023-05-09 23:03:51 INFO Section2ServiceSelectionHandler Starting to selectNumberOfApplicants
2023-05-09 23:03:51 INFO Section2ServiceSelectionHandler Starting to selectFamilyStatus
2023-05-09 23:03:51 INFO Section2ServiceSelectionHandler Starting to clickServiceType
2023-05-09 23:03:51 INFO Section2ServiceSelectionHandler Starting to clickVisaPurpose
2023-05-09 23:03:53 INFO Section2ServiceSelectionHandler Starting to clickToVisa
2023-05-09 23:03:57 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 23:03:57 INFO Section2ServiceSelectionHandler Successfully send form  count is:3
2023-05-09 23:03:57 INFO Section2ServiceSelectionHandler Value of the active step is: 2    
Service selection
2023-05-09 23:03:57 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 3
2023-05-09 23:04:07 INFO Section2ServiceSelectionHandler Starting to fill the form in section 2
2023-05-09 23:04:07 INFO Section2ServiceSelectionHandler Starting to selectCitizenshipValue
2023-05-09 23:04:09 INFO Section2ServiceSelectionHandler Successfully selected the citizenship value
2023-05-09 23:04:09 INFO Section2ServiceSelectionHandler Starting to selectNumberOfApplicants
2023-05-09 23:04:09 INFO Section2ServiceSelectionHandler Starting to selectFamilyStatus
2023-05-09 23:04:09 INFO Section2ServiceSelectionHandler Starting to clickServiceType
2023-05-09 23:04:10 INFO Section2ServiceSelectionHandler Starting to clickVisaPurpose
2023-05-09 23:04:12 INFO Section2ServiceSelectionHandler Starting to clickToVisa
2023-05-09 23:04:15 INFO Section2ServiceSelectionHandler Starting to sendForm
2023-05-09 23:04:15 INFO Section2ServiceSelectionHandler Successfully send form  count is:4
2023-05-09 23:04:16 INFO Section2ServiceSelectionHandler Value of the active step is: 2    
Service selection
2023-05-09 23:04:16 INFO Section2ServiceSelectionHandler Calender page is not opened. Search count: 4
<=========----> 75% EXECUTING [1m 26s]
> :run
