### ISSUE TITLE
Error during calendar page 

### ISSUE THREAD

**Issue by rsilvaberlin** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#53]
Hi

I saw the calendar and date available but nothing happening after that. There is a captcha step after date and dropdown selection. Could that be the reason? 

The log seems to be saying null value at credentials. I am new here so any help would be great. 

2023-05-22 09:26:21 ERROR TerminFinder Exception occurred during the process, quitting.
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.example.formhandlers.Section2ServiceSelectionHandler$$Lambda$640/0x000000080108a310@71e7bc01 (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.0', java.version: '17.0.7'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 113.0.5672.63, chrome: {chromedriverVersion: 113.0.5672.63 (0e1a4471d5ae..., userDataDir: /tmp/.org.chromium.Chromium...}, goog:chromeOptions: {debuggerAddress: localhost:35505}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 113.0.5672.63, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 63aa7156ca12c096fb1b38f4805f3c21
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87) ~[selenium-support-4.8.1.jar:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231) ~[selenium-support-4.8.1.jar:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.selectCitizenshipValue(Section2ServiceSelectionHandler.java:97) ~[main/:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.fillForm(Section2ServiceSelectionHandler.java:71) ~[main/:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.fillAndSendForm(Section2ServiceSelectionHandler.java:59) ~[main/:?]
        at org.example.TerminFinder.fillAndSendFormWithExceptionHandling(TerminFinder.java:111) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:86) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2023-05-22 09:26:23 INFO IoUtils error occurred during getting the secret
2023-05-22 09:26:23 INFO IoUtils File name :TerminFinder_2023-05-22_09:26:23_exception.html, TerminFinder_2023-05-22_09:26:23_exception.png
2023-05-22 09:26:23 INFO IoUtils Getting the page content
2023-05-22 09:26:24 INFO IoUtils Saving source code to file
2023-05-22 09:26:24 INFO IoUtils Saving screenshot
2023-05-22 09:26:24 INFO IoUtils Storing files to s3
2023-05-22 09:26:24 INFO IoUtils Saving has failed. Reason: 
java.lang.NullPointerException: Credentials must not be null.
        at software.amazon.awssdk.utils.Validate.notNull(Validate.java:119) ~[utils-2.20.61.jar:?]
        at software.amazon.awssdk.auth.credentials.StaticCredentialsProvider.<init>(StaticCredentialsProvider.java:30) ~[auth-2.20.61.jar:?]
        at software.amazon.awssdk.auth.credentials.StaticCredentialsProvider.create(StaticCredentialsProvider.java:37) ~[auth-2.20.61.jar:?]
        at org.example.utils.IoUtils.savePage(IoUtils.java:204) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:97) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by rsilvaberlin** [comment]
![TerminFinder_2023-05-22_08:06:01_exception](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/133482345/f946a00b-9e23-464a-9b6d-9ac9becdee7a)

**Comment by rsilvaberlin** [comment]
![TerminFinder_2023-05-22_09:21:24_exception](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/133482345/19619ce7-4c1a-4d0d-ac4f-ccdcecb2fd40)

**Comment by ya-ning** [comment]
I have the same problem. The screenshots show the calendar page but nothing was selected

**Comment by rsilvaberlin** [comment]
@ya-ning can you share your log as well?

**Comment by ya-ning** [comment]
@rsilvaberlin sorry, I killed the container afterward because it's too heavy for my laptop to run, taking up 98% of CPU 🤣  I'll share it again if it happens :) but I have the same screenshots as you (available on 06.06 & 23.05)

**Comment by yilmaznaslan** [comment]
The bot is broken due to the latest update on the website, until fix is implemented

**Comment by rsilvaberlin** [comment]
Thanks @yilmaznaslan.

**Comment by Sh-Nael** [comment]
Hi,
I downloaded the codes and have run it today but facing below errors when it reaches the calendar page (with slots available) and it starts over from the beginning:

2023-07-19 16:26:43 INFO TerminFinder page is saved
2023-07-19 16:26:43 INFO DriverUtils Initializing the driver. Host: localhost, try: 0
Jul 19, 2023 4:26:43 PM org.openqa.selenium.remote.RemoteWebDriver checkNonW3CCapabilities
**WARNING:** Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [unexpectedAlertBehaviour]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jul 19, 2023 4:26:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
**WARNING:** Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [unexpectedAlertBehaviour]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
2023-07-19 16:26:43 INFO DriverUtils Driver is initialized.
2023-07-19 16:26:48 INFO TerminFinder Starting to getHomePage
2023-07-19 16:26:48 INFO TerminFinder Getting the URL: https://otv.verwalt-berlin.de/ams/TerminBuchen?lang=en

**Comment by yassin64b** [comment]
With the newest code I get this output and the bot stops, but no confirmation email from LEA so it was not successful. Before updating today I still got a sound notification and similar error to above, now I also don't get a sound.

```
2023-10-11 18:30:04 INFO Section2ServiceSelectionHandler Page is loaded
2023-10-11 18:30:04 INFO Section2ServiceSelectionHandler Starting to isDateSelectionOpened
2023-10-11 18:30:07 INFO Section2ServiceSelectionHandler Value of the ACTIVE_STEP is: 3Date selection
2023-10-11 18:30:07 INFO Section2ServiceSelectionHandler There is no error message
2023-10-11 18:30:07 INFO Section2ServiceSelectionHandler Calender page is opened and there is no alert
2023-10-11 18:30:07 INFO Section3DateSelectionHandler Starting to: listDatesAndClickToFirstAvailable
2023-10-11 18:30:07 INFO Section3DateSelectionHandler Available date: Day: 12, Month: 9 Year: 2023
2023-10-11 18:30:07 INFO Section3DateSelectionHandler Available date: Day: 12, Month: 9 Year: 2023
2023-10-11 18:30:07 INFO AppointmentFinder End of process
2023-10-11 18:30:09 INFO IoUtils error occurred during getting the secret
2023-10-11 18:30:09 INFO IoUtils File name :date_selection_success_2023-10-11_18:30:09.html, date_selection_success_2023-10-11_18:30:09.png
2023-10-11 18:30:09 INFO IoUtils Getting the page content
2023-10-11 18:30:09 INFO IoUtils Saving source code to file
2023-10-11 18:30:09 INFO IoUtils Saving screenshot
2023-10-11 18:30:09 INFO IoUtils S3 is not  enabled
2023-10-11 18:30:09 INFO Main Appointments found
```

**Comment by yassin64b** [comment]
Also wondering why it is listing Month: 9, which is in the past?

**Comment by yilmaznaslan** [comment]
Yes because of captcha you don't get email but it only plays a sound once termin page is opened, Idk why it didn't play sound

**Comment by allentiak** [comment]
@yilmaznaslan
Shall we either rename this or closing it in favor of #83?
