### ISSUE TITLE
Trying to run gradlew.bat on Win 10

### ISSUE THREAD

**Issue by AlexFundorin** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#6]
Figured out how to run Selenium Hub in Docker:
![image](https://user-images.githubusercontent.com/22612802/227361470-c65d5ece-4214-4fb1-b334-ab7e5ab4318d.png)
Installed JDK17, cause JDK20 was giving errors.
Now, I run gradlew.bat and getting the following error:
'C:\Downloads\berlin-auslaenderbehorde-termin-bot-master>gradlew.bat

> Task :help

Welcome to Gradle 7.4.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see more detail about a task, run gradlew help --task <task>

To see a list of command-line options, run gradlew --help

For more detail on using Gradle, see https://docs.gradle.org/7.4/userguide/command_line_interface.html

For troubleshooting, visit https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed'

How should I properly run the script in Win10?

**Comment by yilmaznaslan** [comment]
I didn't test it in windows. You can install git bash and run the `./gradlew run` in the git bash terminal

**Comment by AlexFundorin** [comment]
Same. 
https://i.imgur.com/lqEiMwq.png

**Comment by AlexFundorin** [comment]
`$ ./gradlew run

> Task :run FAILED
2023-03-24 13:16:57,048 main ERROR No URL provided for HttpAppender: url
2023-03-24 13:16:57,050 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.HttpAppender for element Http org.apache.logging.log4j.core.config.ConfigurationException: Arguments given for element Http are invalid: field 'url' has invalid value 'null'
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.injectFields(PluginBuilder.java:208)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:121)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1000)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:940)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:932)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:551)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:287)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:627)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:700)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:717)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:272)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at org.example.Main.<clinit>(Main.java:16)

2023-03-24 13:16:57,052 main ERROR Null object returned for Http in Appenders.
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (BufferedInputStream); line: 6, column: 91] (through reference chain: org.example.model.VisaFormTO["visaLabelValue"])
        at org.example.utils.IoUtils.readVisaInfoFromFile(IoUtils.java:45)
        at org.example.Main.main(Main.java:20)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (BufferedInputStream); line: 6, column: 91] (through reference chain: org.example.model.VisaFormTO["visaLabelValue"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1822)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:568)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:450)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:363)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:196)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
        at org.example.utils.IoUtils.readVisaInfoFromFile(IoUtils.java:43)
        ... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (BufferedInputStream); line: 6, column: 91]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1094)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2542)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2471)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:302)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:41)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:566)
        ... 9 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-17\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 59s
3 actionable tasks: 3 executed
`

**Comment by AlexFundorin** [comment]
Here:
{
  "isResidencePermitPresent":  false,
  "residencePermitId": "12345678",
  "serviceType": "Apply for a residence title",
  "visaPurposeValue": "Economic activity",
  "visaLabelValue" : "Residence permit for scientific staff and researchers (sect. 18d)»
}

**Comment by AlexFundorin** [comment]
Took master. Rebuilt selenium hub. Ran gradlew via git bash. This is the output:
$ ./gradlew run

> Task :run FAILED
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (BufferedInputStream); line: 6, column: 91] (through reference chain: org.example.model.VisaFormTO["visaLabelValue"])
        at org.example.utils.IoUtils.readVisaInfoFromFile(IoUtils.java:48)
        at org.example.Main.main(Main.java:20)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (BufferedInputStream); line: 6, column: 91] (through reference chain: org.example.model.VisaFormTO["visaLabelValue"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1822)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:568)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:450)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:363)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:196)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
        at org.example.utils.IoUtils.readVisaInfoFromFile(IoUtils.java:46)
        ... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (BufferedInputStream); line: 6, column: 91]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1094)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2542)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2471)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:302)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:41)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:566)
        ... 9 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-17\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
3 actionable tasks: 3 executed

**Comment by AlexFundorin** [comment]
Thanks. Fixed that. Here's the git bash output:
`$ ./gradlew run

> Task :run
Mar 24, 2023 11:19:14 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-03-24 23:19:17 INFO DriverUtils Driver is initialized.
2023-03-24 23:19:17 INFO TerminFinder Verifying form: ResidenceTitleInfoDTO{isResidencePermitPresent=false, residencePermitId='12345678', serviceTyp=Apply for a residence title}
2023-03-24 23:19:17 ERROR TerminFinder Failed validate form: ResidenceTitleInfoDTO{isResidencePermitPresent=false, residencePermitId='12345678', serviceTyp=Apply for a residence title}
Exception in thread "main" org.example.exceptions.FormValidationFailed:
        at org.example.TerminFinder.startScanning(TerminFinder.java:49)
        at org.example.Main.main(Main.java:24)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-17\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
3 actionable tasks: 2 executed, 1 up-to-date
`

**Comment by yilmaznaslan** [comment]
These is the json files you should use depending on if you have residencePermitId already or not
```
{
  "isResidencePermitPresent":  false,
  "residencePermitId": null,
  "serviceType": "Apply for a residence title",
  "visaPurposeValue": "Economic activity",
  "visaLabelValue" : "Residence permit for scientific staff and research workers (sect. 18d)"
}
```

```
{
  "isResidencePermitPresent":  true,
  "residencePermitId": 12345678,
  "serviceType": "Apply for a residence title",
  "visaPurposeValue": "Economic activity",
  "visaLabelValue" : "Residence permit for scientific staff and research workers (sect. 18d)"
}
```

**Comment by AlexFundorin** [comment]
I guess that it's working now. Thank you for helping!
https://i.imgur.com/798OnZp.png

**Comment by AlexFundorin** [comment]
I wonder if the process is going fine, since there are some exceptions being thrown here and there, especially when creating a new session: https://i.imgur.com/C3x4hfk.png

**Comment by AlexFundorin** [comment]
Also, is this the right behavior, when all I can see for the last half an hour is the number of threads listing? 
https://i.imgur.com/aBr6Jst.png

**Comment by yilmaznaslan** [comment]
Looks like the selenium server is not working. Can you make sure that the selenium docker is running ?

**Comment by AlexFundorin** [comment]
It is, as far as I can tell. At least, the GUI says so: https://i.imgur.com/Xj1j1me.png

**Comment by yilmaznaslan** [comment]
Can you access to selenium server via `http://localhost:4444/ui#/sessions` ? Anyway, I would suggest you to delete the selenium docker and re-run it like below;

```
docker run \
  --name selenium \
  --net termin \
  -p 4444:4444 -p 7900:7900 -p 5900:5900 \
  --shm-size="1g" \
  -d \
  -e SE_NODE_MAX_SESSIONS=5 \
  -e SE_NODE_OVERRIDE_MAX_SESSIONS=true \
  -e SE_NODE_SESSION_TIMEOUT=120 \
  -t selenium/standalone-chrome:latest
```

**Comment by AlexFundorin** [comment]
Stuck again with this "Number of threads" list, but the server is reachable. https://i.imgur.com/qnSwpBu.png
Will rebuild the docker now.

**Comment by AlexFundorin** [comment]
Last try:
$ ./gradlew run

> Task :run
Mar 25, 2023 4:51:31 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Host info: host: 'RTVI', ip: '172.31.192.1'
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-blink-features=Au..., --disable-infobars, --start-maximized, --disable-extensions], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-blink-features=Au..., --disable-infobars, --start-maximized, --disable-extensions], extensions: []}}}]
Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-blink-features=Au..., --disable-infobars, --start-maximized, --disable-extensions], extensions: []}}
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
        at org.example.utils.DriverUtils.initDriverHeadless(DriverUtils.java:44)
        at org.example.Main.main(Main.java:22)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:4444
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        ... 5 more
Caused by: java.net.ConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:4444
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:4444
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-17\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by yilmaznaslan** [comment]
Well, again the issue is in your local selenium server. Either it doesn't work correctly or because of the system settings, you can't access port 4444.

Replace the following line
 
https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/blob/c23cfc98d03d848291150f7759f822a99d038cce/src/main/java/org/example/utils/DriverUtils.java#L33

with

``` String seleniumDriverHost = "ec2-34-234-95-142.compute-1.amazonaws.com"; ````

It is a test server I am running in the cloud

**Comment by AlexFundorin** [comment]
I created docker image with the instruction from this repository (the original one)
Don't see any errors now and it seems like running. Please, check:
$ ./gradlew run

> Task :run
Mar 25, 2023 5:37:46 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-03-25 17:38:07 INFO DriverUtils Driver is initialized.
2023-03-25 17:38:07 INFO TerminFinder Verifying form: ResidenceTitleInfoDTO{isResidencePermitPresent=false, residencePermitId='null', serviceTyp=Apply for a residence title}
2023-03-25 17:38:07 INFO TerminFinder Successfully validated form: ResidenceTitleInfoDTO{isResidencePermitPresent=false, residencePermitId='null', serviceTyp=Apply for a residence title}
2023-03-25 17:38:07 INFO TerminFinder Scheduled the task at rate: 1000
2023-03-25 17:38:07 INFO ThreadMonitor Number of threads: 6
2023-03-25 17:38:07 INFO TerminFinder Switching to a new tab
2023-03-25 17:38:16 INFO TerminFinder Getting the URL: https://otv.verwalt-berlin.de/ams/TerminBuchen?lang=en
2023-03-25 17:38:16 INFO TerminFinder Window handle: CDwindow-1CF1BD5EBE7CB5D5AF5E344A9330642C
2023-03-25 17:38:16 INFO TerminFinder Window handle: CDwindow-61D1E8F8FC0E9B4889B0E3EBD80D33EE
2023-03-25 17:38:16 INFO TerminFinder Closing the  window handle: CDwindow-1CF1BD5EBE7CB5D5AF5E344A9330642C
2023-03-25 17:38:21 INFO TerminFinder Switching to window handle: CDwindow-61D1E8F8FC0E9B4889B0E3EBD80D33EE
2023-03-25 17:38:37 INFO ThreadMonitor Number of threads: 6
2023-03-25 17:38:41 INFO Section1MainPageHandler Starting to fill the form
2023-03-25 17:38:44 INFO LogUtils Element: Book Appointment, Process:GETTING_BY_ID, Status:SUCCESSFUL
2023-03-25 17:39:03 INFO LogUtils Element: Book Appointment, Process:CLICKING_TO_ELEMENT, Status:Successful
2023-03-25 17:39:07 INFO ThreadMonitor Number of threads: 5
<=========----> 75% EXECUTING [1m 39s]
> :run

**Comment by AlexFundorin** [comment]
Seems like some errors, again - https://i.imgur.com/499C4UW.png
Sorry for taking so much of your time.

**Comment by yilmaznaslan** [comment]
You can ignore those io-related logs as long as the application is running. I can confirm from my monitoring that your application is currently running on the remote selenium server

**Comment by AlexFundorin** [comment]
So, is there a way I could run the server locally? I disabled firewall yesterday, so it shouldn't have interfered.

**Comment by yilmaznaslan** [comment]
I am sorry I can't really help with that further :/

**Comment by AlexFundorin** [comment]
That's fine. Thank you!

**Comment by AlexFundorin** [comment]
Is it fine that the script is throwing out an error on the calendar step?
https://i.imgur.com/6HzOcb8.png

**Comment by yilmaznaslan** [comment]
The form is submitted, it is not an error. You can see the automated fillings in http://localhost:4444/ui#/sessions -> click to session -> password: secret
